version: '3.5'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.6
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./tmp/clickhouse-data:/opt/clickhouse/data
    networks:
      - default

networks:
  default:
